#!/bin/bash

# выйти, если какая-либо команда не удалась
set -e

if (( $# != 2 )); then
    echo "Недопустимое количество параметров, использование: venv-uninstall <ПАКЕТ> <КОМАНДА>"
    exit 1
fi
 
PACKAGE=$1
COMMAND=$2

echo "Удаление пакета '$PACKAGE' с помощью команды '$COMMAND'..."

VENV_PATH=~/.venvs/$PACKAGE
BIN_PATH=$HOME/.local/bin
COMMAND_BIN_PATH=$BIN_PATH/$COMMAND

# проверить, существует ли venv
if test -d "$VENV_PATH"; then
  echo "Удаление venv '$VENV_PATH' ..."
  rm -r $VENV_PATH
else
  echo "Каталог VENV не существует, игнорируя"
fi

if test -L "$COMMAND_BIN_PATH"; then
  echo "Удаление '$COMMAND_BIN_PATH' ..."
  rm $COMMAND_BIN_PATH
else
  echo "$COMMAND_BIN_PATH файл не существует, игнорирую"
fi

echo "Сделанный"
